---
title: 异常处理
date: 2018-08-05 19:50:22
tags: [异常,exception]
categories: python
---

默认情况下，Python程序在运行过程中，当遇到异常时程序会停止运行，并抛出异常信息，后续代码不会被执行。

```python
print("程序运行中...")
print(6 / 0)     
print("小火车来了,呜呜呜...")

"""
程序运行中...
Traceback (most recent call last):
  File "E:/test.py", line 2, in <module>
    print(6 / 0)
ZeroDivisionError: division by zero
"""
```



Python中的常见异常类型有IndexError，NameError，ValueError，TypeError，AttributeError，父类是Exception。

```python
arr = [1, 2, 3]
print(arr[3])        

"""
Traceback (most recent call last):
  File "E:/test.py", line 2, in <module>
    arr[3]
IndexError: list index out of range
"""
```



#### 捕获异常

由于出现异常会中断程序的执行，而这是我们不希望看到的。try-except语句可以用来处理这个问题，从而保证遇到异常时，程序保持正常运行。

```python
"""
语法:
try:
	可能会出现异常的代码
except 异常类型 as 变量:
	处理异常/pass
"""
#变量是异常类型的一个实例

print("程序运行中...")
try:
    print(6 / 0)          
except ZeroDivisionError as err:
    print(err)
print("小火车来了,呜呜呜...")

"""
程序运行中...
division by zero
小火车来了,呜呜呜...
"""
```



except后面的异常类型必须和可能出现异常的代码中的异常类型匹配，否则程序遇到异常依然会中断。如果无法预知可能出现的异常类型，可以使用Exception类型或者不跟异常类型，可以自动匹配系统中常见的异常类型。

```python
print("程序运行中...")
try:
    print(6 / 0)          
except Exception as err:
    print(err)
print("小火车来了,呜呜呜...")

"""
程序运行中...
division by zero
小火车来了,呜呜呜...
"""
```



一个try-except语句只能处理一个异常，当可能出现多个异常时，使用多个try-except语句分别处理。

```python
print("程序运行中...")
try:
    print(6 / 0)          
    arr = [1, 2, 3]
    print(arr[3])       
except ZeroDivisionError as err:
    print(err)
print("小火车来了,呜呜呜...")

"""
程序运行中...
division by zero
小火车来了,呜呜呜...
"""

#虽然程序正常运行了，但是异常代码后面的代码却没有被执行。
```



try-except-finally语句中，无论程序中是否出现异常，finally后面的代码总是会被执行。



#### 抛出异常

```python
#raise抛出一个异常对象，程序中断

raise ValueError("Invalid value")

"""
Traceback (most recent call last):
  File "E:/test.py", line 1, in <module>
    raise ValueError("Invalid value")
ValueError: Invalid value
"""

#可以用try-except语句处理raise抛出的异常

try:
    raise ValueError("Invalid value")
except ValueError as err:
    print(err)
    
#Invalid value
```



#### 自定义异常

自定义异常类型和定义一个类相同，只是一般直接或间接继承自Exception。

```python
class CustomError(Exception):
    pass

try:
    raise CustomError("自定义异常")
except CustomError as err:
    print(err)
    
#自定义异常
```